### ISSUE TITLE
Firebaseの準備

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#11]
## 概要

- [x] Firebaseプロジェクトを作成(dev/prd)
- [x] dev：Firestoreの初期設定および、iOS/Androidのアプリを追加
- [x] Flutter側でパッケージを追加し、Firebase構成ファイル(GoogleService.json)を追加しビルド確認する
- [x] 各メンバーに適切な権限を与え、json/plistを取得できるようにする

＊↑の幾つかは`flutterfire configure`で出来るかも?

## 期限

- 2022/11/1

**Comment by Ta23ka98** [comment]
@taisei-kuro 
プロジェクト作成など、こちらでやる作業が終わり次第またお伝えします🙋

**Comment by Ta23ka98** [comment]
@hirom0922
#11 に取り掛かりたいと思っています。

前回の共同開発では、
・ Firebaseプロジェクトを作成(dev/prd) ←リーダーが作成
・dev：Firestoreの初期設定および、iOS/Androidのアプリを追加 ←リーダーが追加
・Flutter側でパッケージを追加し、Firebase構成ファイル(GoogleService.json)を追加しビルド確認する ←メンバー
・各メンバーに適切な権限を与え、json/plistを取得できるようにする ←メンバー

という感じでやっていました。(この時、自分はメンバー側でした)
flavor対応自体は、リリース前にやる感じで大丈夫でしょうか？🤔

[こんぶ さんがflavor対応の記事のリンク](https://zenn.dev/susatthi/articles/20220904-151314-flutter-fire-flavor)を載せてくれていましたが、これは初めからflavor対応しないといけないやり方の気がします…
たいせい さんにアサインするつもりですが、もしこのやり方が難しすぎる場合は
・自分がやる
・hiromさんにお願いする
・この記事のやり方を使わず、リリース前に別の方法でflavor分けする
のどれかでやろうと思っています

**Comment by Ta23ka98** [comment]
メモ：リリース前に対応(定期MTGで確認)

**Comment by Ta23ka98** [comment]
@taisei-kuro 
Firebaseの権限付与ができました！
確認メールが届いていると思います👍

つきましては、
・iOS/Androidのアプリを追加
・Firebaseパッケージを追加し、ビルドが出来るか確認
をお願いします🙌

とりあえず「編集者」の権限を付与しましたが、アプリの追加などできなかったら仰って下さい🙇

**Comment by taisei-kuro** [comment]
・iOS/Androidのアプリを追加
→完了

・Firebaseパッケージを追加し、ビルドが出来るか確認
→完了

**Comment by Ta23ka98** [comment]
@taisei-kuro 
勘違いしていたのですが、ブランチを作ってマージする必要がありそうです🙇

お手数ですが、
・ブランチ作成(developから`feature/#11_firebase_setup`)
・プルリク作成
(コードレビュー)
・マージ
という流れをお願いします🙋
