### ISSUE TITLE
AR機能の実装に使えるパッケージの調査・選定

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#15]
## 概要

- AR機能の実装に使えるパッケージの調査・選定

## 要件

このタスクでは、
- ①以下のパッケージ以外に、使えそうなパッケージがないかリサーチする
- ②リサーチ後、それぞれのパッケージが今回のアプリに適切か判断/必要であれば詳細をリサーチする
- ③適切そうなパッケージを選び、実際に試作してみる
＊試作はこのリポジトリではなく、別リポジトリでサンプルアプリを作る

今回のアプリに必要な機能
 - 「FloatingActionButtonを押すと、足元にリングが作成される」
 - 「ARカメラを起動すると、そのリングが確認できる」
 - 「そのリングに対してタップ？などで確認できる」
など。

備考
・#17 では別パッケージのリサーチ中

## 使えそうなパッケージ一覧
・[arcore_flutter_plugin: ^0.0.11](https://pub.dev/packages/arcore_flutter_plugin#-readme-tab-)
・[arkit_plugin: ^1.0.5](https://pub.dev/packages/arkit_plugin)
・[ar_flutter_plugin: ^0.7.1](https://pub.dev/packages/ar_flutter_plugin)
・[ar_location_view: ^2.0.2](https://pub.dev/packages/ar_location_view)

## 参考記事
・[Augmented Reality with Flutter.](https://medium.flutterdevs.com/augmented-reality-in-flutter-1153b0ef2758)
・[[Flutter開発]FlutterとARKitを組み合わせてiPhoneのARアプリを作成してみる](https://qiita.com/s_harada/items/18bec5db482ab1e2d92c)

## 期限

来週までに使うパッケージが決まると良さそう

**Comment by Ta23ka98** [comment]
@Tomohiro629 
Issueの通り、まずは①に取り掛かって頂きたいです🙋
具体的には、既に挙がっているパッケージ以外の調査です。
(なぜかというと、自分で調べたパッケージよりKokiさんのパッケージの方が良さそうだったので...)

そこがクリアし次第、「今回のアプリに必要な機能」を満たせそうなパッケージの選定・調査をお願いします🙇

最後に、実際に最低限の機能を実装できるか試作するステップになります🙌

**Comment by Tomohiro629** [comment]
@Ta23ka98 
昨日はお疲れさまでした！

現状の進捗状況報告します。
Androidでの開発環境です。

・「FloatingActionButtonを押すと、足元にリングが作成される」
→ ar_flutter_pluginを使って可能

・「ARカメラを起動すると、そのリングが確認できる」
→　調査した中で確認できず。
　　データベースから値の取得する必要はある

・「そのリングに対してタップ？などで確認できる」
→　ar_flutter_pluginでのタップ機能がなさそう。(arcoreにはあるがコンパイルエラーでうまくいってない)

リング確認とタップはARではなくStackでカメラ画面にオブジェクトを重ねたらいけそう。
その場合カメラの動きに合わせて動くとかはできない。

現状こんな感じです。
引き続きパッケージ調査とarcoreの導入をします。

**Comment by Tomohiro629** [comment]
続き

自分のリポジトリにar_camera_demoおいてます。
ar_location_viewはうまくカメラ画面表示できてないです。

**Comment by Ta23ka98** [comment]
@Tomohiro629 
進捗報告ありがとうございます👍
なんとなく状況が掴めてきました！

MTGでも仰っていましたが、
・パッケージの更新がされていない
・ビルド自体が難しい
などでAR Coreの導入は厳しそうですね🤔

[ar_location_view](https://pub.dev/packages/ar_location_view)の存在は知りませんでした！
更新履歴を見たところ、かなり新しいパッケージみたいですね

次のMTGまでには、どちらを採用するか決まると良さげですね👍

引き続き、
・ar_flutter_plugin
・ar_location_view
の調査をお願いします🙌

**Comment by ke158** [comment]
ar_location_view: ^2.0.2調査

[プロジェクトURL](https://github.com/ke158/ar_location_view_sample)

ARカメラ起動後、緯度と経度からオブジェクト配置(stackでオブジェクトを位置指定した場合エラー確認)
オブジェクトをタップで画面遷移

**Comment by ke158** [comment]
https://user-images.githubusercontent.com/74230682/198915196-fe8f0a7d-42cf-4c5a-a751-c1464bb69df7.mp4

**Comment by Ta23ka98** [comment]
@ke158 @Tomohiro629 
2人ともお疲れ様です🙌
どちらのサンプルもクローンして確認させて頂きました！

まだ確認できていない部分もありますが、必要な機能が実装できそうでよかったです👍
次の定期MTGでは、画面共有などで他メンバーにも共有できれば面白そうです！

各デバイス(iOS/Android)に使用するパッケージは決定したという認識でよさそうでしょうか？🤔
