### ISSUE TITLE
マップパッケージの選定

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#19]
## 概要

アプリ開発に必要なマップパッケージを選定する。

## 要件

今回のアプリに必要な機能としては...

・現在地を基準にマップを表示する
・Firestoreのデータをマップ上に表示する(ピンなどで)

など。
以下の記事を参考に、必要なパッケージの選定をお願いします。

## 参考記事
https://zenn.dev/odaken/articles/615f12930c7f5d

**Comment by hirom0922** [comment]
ありがとうございます。
google_maps_flutterにします。
一応、ピン立てるサンプルは動かしてみました。

**Comment by Ta23ka98** [comment]
了解です！
またAPIキーを生成したらお知らせします🙋
(以後のやりとりは #18 へ)
