### ISSUE TITLE
Map画面のUIと機能についての検討

### ISSUE THREAD

**Issue by hirom0922** [Ta23ka98/life_snap#22]
簡単なものですが、画面サンプルを作ったので、上げておきます。

<img width="397" alt="image" src="https://user-images.githubusercontent.com/90263627/199264232-eef86548-aaf9-447e-a588-d308484ef276.png">

Mapのマーカーについては、吹き出しはつけれる。タップイベントも可能。
吹き出し内容については、正確な地図名称を出力するのはどうしたら良いものか。

**Comment by Ta23ka98** [comment]
かなりいい感じだと思います！
GoogleMapもリッチに見えて良いですね👍

GCPのクイックビルダーというサンプルを見ていると、複数のAPIを組み合わせられそうです🤔
google_maps_flutterで同じことができるか出来るかわかりませんが...
<img width="1377" alt="スクリーンショット 2022-11-02 0 11 33" src="https://user-images.githubusercontent.com/79580546/199267725-60d8c20d-552d-46ed-9c3b-4897143f51d4.png">

**Comment by hirom0922** [comment]
ありがとうございます。
パッケージやアーキテクチャーの方ばかり見ていたのですが、
今週の進捗発表が難しくなりそうなので、
画面を一旦起こしました。

いただいたGCPも参考に、
面白い要素を加えられないかも見ていきますね。
