### ISSUE TITLE
ログイン・会員登録機能の実装

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#26]
## 概要

FirebaseAuthを使った、メールアドレス/パスワードによる認証機能の実装。
既に実装したFirstPageについて、ログイン・会員登録機能の実装をする。

## 要件

・ログイン機能
・会員登録機能
(エラーハンドリングなどは実装しなくてOKです)

**Comment by KonSan0722** [comment]
一応firebaseAuthのメールアドレス、パスワードでの認証機能完了しました。
現在自分のリポジトリ内で行なっているため、ご都合の良い日に挙動を確認していただいてもいいでしょうか？

**Comment by Ta23ka98** [comment]
@KonSan0722 
おけです！
よければ明日のMTG後はいかがでしょうか？🤔

**Comment by KonSan0722** [comment]
OKです！よろしくお願いします！（エラーハンドリングは一部分だけ軽くはしていますが、featureブランチに書き込むときは書きません！）
