### ISSUE TITLE
AR機能に関するiOS/Androidバージョンの制約の調査

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#27]
## 概要

ar_location_viewのドキュメントなどを参考に、iOS/Androidのバージョンの制約を調査する。

## 要件

・ar_location_viewを導入するにあたり、iOS/Androidはどのバージョン以降に動作可能か
・アプリをリリースするにあたり、サポートするiOS/Androidバージョンをどうやって設定するか

**Comment by Tomohiro629** [comment]
バージョンの制約に関する情報の記載見つからず・・・

**Comment by Ta23ka98** [comment]
なるほどです！
自分も確認してみたのですが、特に記載なかったです

たぶんiOS/AndroidネイティブのAR機能を呼び出さず、独自に機能を実装して再現してるんだと思います🤔
またMTGで確認して、特記することがなければクローズしておきます🙋

**Comment by Tomohiro629** [comment]
りょーかいです👍
