### ISSUE TITLE
再認証画面(機能)の実装

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#51]
## 概要

再認証画面の実装(機能)。
アカウント削除機能および、それに必要な再認証機能を実装する。

## 要件

 - パスワード入力フォーム：入力されたパスワードを使い、↓
 - アカウント削除ダイアログ：「削除する」ボタンで実際にアカウントを削除する

<img width="705" alt="スクリーンショット 2022-11-15 17 21 45" src="https://user-images.githubusercontent.com/79580546/201868678-46a9ccec-0ccb-4499-937f-8ad6d1621ede.png">

## 参考記事
・再認証に関するドキュメント
(https://firebase.flutter.dev/docs/auth/usage/#reauthenticating-a-user)

## 期限

- 2022/12/08

**Comment by Ta23ka98** [comment]
@KonSan0722 
こちらアサインしました！
スキーマ決まってないと実装できないと思ってたのですが、こちらはAuthにしか関わらないので実装できそうでした😅

再認証機能＆アカウント削除機能を実装して頂くのですが、ユーザデータは削除しなくてOKです🙆

**Comment by KonSan0722** [comment]
了解です！ひとまず昨日pullしたdevelopeからfeatureブランチを作成して作業しますが、APIキーの部分は申し訳ないですが火曜日によろしくお願いします💦

**Comment by Ta23ka98** [comment]
OKです！
また火曜21時にGatherでお待ちしてます👍
