### ISSUE TITLE
ログイン状態を監視する

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#52]
## 概要

ログイン状態を監視し、未ログイン状態だと未ログイン画面へ遷移する。

## 要件

*画像はイメージです
<img width="478" alt="スクリーンショット 2022-11-15 17 33 00" src="https://user-images.githubusercontent.com/79580546/201869667-93b467c0-9217-4b34-9474-fa58ac032006.png">

## 期限

- 2022/11/24

**Comment by Ta23ka98** [comment]
@KonSan0722 
こちらスクショ古いですが、ログイン状態によって未ログイン画面/メイン機能の画面への遷移を実装お願いします🙋
(見落としてるだけで実装済みかもしれませんが...)

**Comment by KonSan0722** [comment]
あれ、見落としていました、、
別途futurebranch作成し、対応してみます！

**Comment by KonSan0722** [comment]
すみません、前のプルリクでエラーなど色々解消していて、そちらを先にレビューしていただくことは可能でしょうか🙇🙇
developeに謎のwidth、heightのエラーが残っていて、そのエラーをこの間のプルリクで修正したのですが、今回featureブランチを作成するにあたってまた修正したらコンフリクトを起こしそうなので、、
よろしくお願いします！

**Comment by KonSan0722** [comment]
それか、すでにプルリクとして出しているfeature73の方でそのまま実装してもよろしいでしょうか？

**Comment by Ta23ka98** [comment]
了解です！
プルリクは別で分けておきたいので、ひとまずレビューしたいと思います👍

**Comment by KonSan0722** [comment]
了解です！
今feature73の方で試しに実装してみて挙動的にはうまくいったと思うので、そちらのコードをまた別途developeからpullして作成したfeatureブランチにコピぺしてプルリクを出します！

**Comment by Ta23ka98** [comment]
## 参考記事
https://qiita.com/granoeste/items/19c119ffc36a016e6223
