### ISSUE TITLE
仮マイページを実装する

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#53]
## 概要

仮のマイページを実装する。
アカウントの再認証＆削除する画面を実装するため。

## 要件

 - Body：
   - アイコン + ユーザ名：タップで再認証画面(#50)へ遷移

<img width="254" alt="スクリーンショット 2022-11-15 17 37 27" src="https://user-images.githubusercontent.com/79580546/201870898-0fc2d469-3f15-4eab-83fb-5f63fac27bbb.png">

## 期限

- 2022/11/20

## 親ストーリー

#39

**Comment by Ta23ka98** [comment]
@KonSan0722 
概要にも書いてありますが、本来のマイページは #39 です。
ただ後々Kokiさんに再認証&アカウント削除画面を実装して頂くので、それに先駆けマイページの一部だけ実装して頂きたいです👍

(AppBarとボトムナビゲーションに関しては実装不要です)

**Comment by KonSan0722** [comment]
すみません、内容が把握できておらず、、
ボトムナビゲーションなしの
画像のようなappbar、(Twitterのように)アイコン、名前の列をクリックすると画面遷移するようなUIをpresentationの中にmy_pageディレクトリを新たに作って、実装すればよいでしょうか？

**Comment by Ta23ka98** [comment]
AppBarも無しでOKです👍

このスクショのような感じです。これがマイページになります。

> 画像のようなappbar、(Twitterのように)アイコン、名前の列をクリックすると画面遷移するようなUIをpresentationの中にmy_pageディレクトリを新たに作って、実装すればよいでしょうか？

これは仰る通りでOKです！

<img width="349" alt="スクリーンショット 2022-11-15 22 16 20" src="https://user-images.githubusercontent.com/79580546/201929006-2bc9fa0f-e5b9-4e04-9365-b0a2daccdd2d.png">

**Comment by Ta23ka98** [comment]
すみません。お伝え忘れていましたが、ユーザ名の代わりにEmailなどを仮表示してもOKです🙆
(後にログイン状態の監視なども行うため)

**Comment by KonSan0722** [comment]
了解です！理解力なくすみません泣
取り組んでみます！

**Comment by Ta23ka98** [comment]
@KonSan0722 
もし詰まってるところがあれば、気軽に相談してOKです👍
よければ今日あたり、Gatherで相談OKですがいかがでしょう🤔
