### ISSUE TITLE
マイページの実装(UI)

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#66]
## 概要

マイページのUIを実装する。
いいねした投稿一覧画面は未実装のため、画面遷移はまだ実装しなくてOK。

## 要件

#53 仮マイページにて一部実装済のため、
・他の要素を実装する
・「マイページ」という名前にリファクタリングする
これらを実施する。

 - Body
   - ユーザアイコン + ユーザ名
   - アイコン +  投稿一覧
   - アイコン +  いいねした投稿
   -  アイコン + アカウント管理

*1：AppBar、BottomNavigationBarは実装しなくてOK(実装済み。あとで繋げる)
*2：「ユーザアイコン + ユーザ名」に関しては、 #53 にて一応実装済み。上記のように、こちらを使用してほしい
まだログイン中のユーザを表示する機能は未実装なので、そこは仮マイページのダミーでOKです🙆

<img width="289" alt="スクリーンショット 2022-11-25 20 12 33" src="https://user-images.githubusercontent.com/79580546/203973591-80e53159-6047-45f5-9991-a3a8be510a8c.png">

## 期限
 - 2022/12/08

**Comment by Ta23ka98** [comment]
@Tomohiro629 
昨日言ってたマイページのUIをアサインしました！
説明がややこしいと思うので、分からないことがあれば聞いて下さってOKです🙆

**Comment by Ta23ka98** [comment]
@Tomohiro629
昨日言ってたマイページのUIをアサインしました！
説明がややこしいと思うので、分からないことがあれば聞いて下さってOKです🙆

**Comment by Ta23ka98** [comment]
Githubスレッドの通知が来ない不具合があったので、修正しました🙌(サンプル)

**Comment by Ta23ka98** [comment]
@Tomohiro629
昨日言ってたマイページのUIをアサインしました！
説明がややこしいと思うので、分からないことがあれば聞いて下さってOKです🙆

(たぶんメールで3回くらい通知来てると思います、すみません🙇)

**Comment by Tomohiro629** [comment]
了解です！
ありがとうございます！

**Comment by Tomohiro629** [comment]
早速質問なんですけどMyPageTentativeを書き換える・追加するってことで合ってますか？

**Comment by Ta23ka98** [comment]
それで間違いないです👍
すみません、先にお伝えしておくべきでした🙇

**Comment by Tomohiro629** [comment]
わかりました。
ありがとうございます！
