### ISSUE TITLE
いいねした投稿一覧・確認画面(UI・機能)の実装

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#67]
## 概要

①いいねした投稿リストが表示される画面
②その確認画面
③ ①→②の画面遷移機能
これらを実装する。

＊UI・機能の実装のため、実際のデータを表示するところまで実装してください。

## 要件

 - AppBar：「ブックマーク一覧」
 - Body：ブックマークした投稿のリスト
   - タイトル
   - 写真
   - いいね
   - 説明文

<img width="729" alt="スクリーンショット 2022-11-25 20 13 36" src="https://user-images.githubusercontent.com/79580546/203973890-1362a15d-f9ab-4ba8-a82b-2ee20d4831e5.png">

**Comment by Ta23ka98** [comment]
@Tomohiro629 
マイページの実装が終わったので、ひとまずアサインさせて頂きました🙋‍♂️
・いいねした投稿一覧画面
・その確認画面
のUI・機能のタスクですが、機能部分は けーさん担当でもいいかもですね🤔

その辺は話し合って頂き、やりやすい方法でお願いします👍

**Comment by Tomohiro629** [comment]
了解です！
