### ISSUE TITLE
画面遷移を実装する

### ISSUE THREAD

**Issue by Ta23ka98** [Ta23ka98/life_snap#73]
## 概要

既に実装されたUIを画面遷移によって繋げる。
また、「ユーザアイコン+ユーザ名」で画面遷移しないよう修正する。

## 要件
スクショのように、画面遷移を繋いでいく。
ただし、
・マップ画面(とカメラ・ARカメラ画面)
・いいねした投稿一覧画面
は一部未実装のため、まだ繋がなくてよい。

加えて「ユーザアイコン+ユーザ名」で画面遷移しないよう修正する。
<img width="739" alt="スクリーンショット 2022-12-11 20 53 15" src="https://user-images.githubusercontent.com/79580546/206902104-21dbb27f-0acc-4b91-8e5b-7526f052b620.png">

**Comment by Ta23ka98** [comment]
@KonSan0722 
早速こちらアサインしました🙋‍♂️

基本的には
・マイページ
→投稿一覧画面
→アカウント管理(再認証画面)
以降の画面遷移を繋いでもらうイメージです。

また先ほどのGatherで仰っていた画面遷移についても修正をお願いします👍

**Comment by KonSan0722** [comment]
先ほどはありがとうございました！やってみます！
